version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo/db:/data/db
      
  redisdb:
    image: redis:7
    command: ['redis-server', '--requirepass', 'redis-password']
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
